import DocsLayout from "@/components/docs/DocsLayout";

export default function SeoMetaPage() {
    return (
        <DocsLayout
            title="SEO Meta Pack"
            description="Learn how Recuvix generates meta tags and schema markup to boost your search rankings."
            breadcrumbs={[
                { label: "Guides", href: "/docs" },
                { label: "SEO Meta Pack", href: "/docs/guides/seo-meta" }
            ]}
        >
            <h2 id="what-is-included">What's included in the Meta Pack?</h2>
            <p>
                Every blog generated by Recuvix comes with a complete SEO pack designed for maximum visibility:
            </p>
            <ul>
                <li><strong>Meta Title & Description</strong>: Optimized for CTR and keyword relevance.</li>
                <li><strong>SEO-Friendly Slug</strong>: Clean, readable URL structures.</li>
                <li><strong>Open Graph Tags</strong>: For perfect sharing on Facebook, LinkedIn, and WhatsApp.</li>
                <li><strong>Twitter Cards</strong>: Rich previews for X (formerly Twitter).</li>
                <li><strong>JSON-LD Schema</strong>: Article and FAQ schema markup for rich search results.</li>
            </ul>
        </DocsLayout>
    );
}
