"use client";

import React, { useEffect, useState } from 'react';
import { createClient } from '@/lib/supabase/client';
import { useWorkspace } from '@/context/WorkspaceContext';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import {
    FileText,
    Users,
    Zap,
    ArrowUpRight,
    Clock,
    ChevronRight,
    TrendingUp
} from 'lucide-react';
import Link from 'next/link';
import { cn } from '@/lib/utils';
import { WorkspaceActivityFeed } from '@/components/workspaces/WorkspaceActivityFeed';

export default function WorkspaceDashboard() {
    const { activeWorkspace } = useWorkspace();
    const supabase = createClient();
    const [blogCount, setBlogCount] = useState<number | null>(null);
    const [memberCount, setMemberCount] = useState<number | null>(null);

    useEffect(() => {
        if (!activeWorkspace) return;

        async function fetchStats() {
            try {
                // Fetch member count
                const { count: membersCount, error: mError } = await supabase
                    .from('workspace_members')
                    .select('*', { count: 'exact', head: true })
                    // We know activeWorkspace is not null here due to the check on line 28
                    .eq('workspace_id', activeWorkspace!.id)
                    .neq('status', 'removed');

                if (!mError && membersCount !== null) setMemberCount(membersCount);

                // Fetch team blogs count
                const { count: blogsCount, error: bError } = await supabase
                    .from('user_blogs')
                    .select('*', { count: 'exact', head: true })
                    .eq('workspace_id', activeWorkspace!.id);

                if (!bError && blogsCount !== null) setBlogCount(blogsCount);
            } catch (error) {
                console.error("Failed to fetch workspace stats", error);
            }
        }

        fetchStats();
    }, [activeWorkspace?.id, supabase]);

    if (!activeWorkspace) return null;

    const stats = [
        { label: 'Team Blogs', value: blogCount !== null ? blogCount.toString() : '-', icon: FileText, color: 'text-purple-500', trend: 'Total generated' },
        { label: 'Team Members', value: memberCount !== null ? memberCount.toString() : '-', icon: Users, color: 'text-blue-500', trend: `${activeWorkspace.max_members} max capacity` },
        { label: 'Credits Remaining', value: activeWorkspace.credits_balance.toString(), icon: Zap, color: 'text-amber-500', trend: 'Auto-refill enabled' },
    ];

    return (
        <div className="space-y-8">
            <header className="flex flex-col md:flex-row md:items-center justify-between gap-4">
                <div>
                    <h1 className="text-3xl font-bold tracking-tight">Dashboard</h1>
                    <p className="text-muted-foreground">
                        Welcome back to <span className="text-foreground font-medium">{activeWorkspace.name}</span>
                    </p>
                </div>
                <div className="flex items-center gap-3">
                    <Link href="/">
                        <Button className="gap-2">
                            <Zap className="size-4" />
                            New Blog
                        </Button>
                    </Link>
                </div>
            </header>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                {stats.map((stat) => (
                    <Card key={stat.label}>
                        <CardHeader className="flex flex-row items-center justify-between pb-2">
                            <CardTitle className="text-sm font-medium text-muted-foreground">
                                {stat.label}
                            </CardTitle>
                            <stat.icon className={cn("size-4", stat.color)} />
                        </CardHeader>
                        <CardContent>
                            <div className="text-2xl font-bold">{stat.value}</div>
                            <p className="text-xs text-muted-foreground mt-1 flex items-center gap-1">
                                <TrendingUp className="size-3 text-green-500" />
                                {stat.trend}
                            </p>
                        </CardContent>
                    </Card>
                ))}
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
                <Card className="lg:col-span-2">
                    <CardHeader className="flex flex-row items-center justify-between">
                        <div>
                            <CardTitle>Recent Team Blogs</CardTitle>
                            <CardDescription>Latest articles generated by your team</CardDescription>
                        </div>
                        <Link href="/history">
                            <Button variant="ghost" size="sm" className="gap-1">
                                View all <ChevronRight className="size-4" />
                            </Button>
                        </Link>
                    </CardHeader>
                    <CardContent>
                        <div className="rounded-lg border bg-muted/30 p-8 text-center">
                            <FileText className="size-12 text-muted-foreground mx-auto mb-4 opacity-20" />
                            <h3 className="text-lg font-medium">No team blogs yet</h3>
                            <p className="text-sm text-muted-foreground mb-6">Start collaborating by creating your first team blog.</p>
                            <Link href="/">
                                <Button variant="outline" size="sm">Create First Blog</Button>
                            </Link>
                        </div>
                    </CardContent>
                </Card>

                <Card>
                    <CardHeader>
                        <CardTitle className="flex items-center gap-2">
                            <Clock className="size-5 text-muted-foreground" />
                            Recent Activity
                        </CardTitle>
                        <CardDescription>What's happening in your team</CardDescription>
                    </CardHeader>
                    <CardContent>
                        <WorkspaceActivityFeed workspaceId={activeWorkspace.id} limit={8} />
                    </CardContent>
                </Card>
            </div>
        </div>
    );
}
