export interface LanguageConfig {
    code: string;
    name: string;
    nativeName: string;
    flag: string;
    direction: "ltr" | "rtl";
    script: "latin" | "devanagari" | "arabic" | "cjk" | "hangul" | "cyrillic";
    primaryCountry: string;
    hreflang: string;
    locale: string;
    googleSearchLocale: string;
    fontStack: string;
    seo: {
        titleMaxChars: number;
        descMaxChars: number;
        keywordStyle: "space_separated" | "comma_separated";
    };
    writingInstructions: string;
    localContext: {
        currency: string;
        currencySymbol: string;
        dateFormat: string;
        exampleBrands: string[];
        searchEngines: string[];
        socialPlatforms: string[];
    };
}

export const LANGUAGES: LanguageConfig[] = [
    {
        code: "en",
        name: "English",
        nativeName: "English",
        flag: "🇺🇸",
        direction: "ltr",
        script: "latin",
        primaryCountry: "USA",
        hreflang: "en",
        locale: "en_US",
        googleSearchLocale: "en-US",
        fontStack: "var(--font-sans), sans-serif",
        seo: {
            titleMaxChars: 60,
            descMaxChars: 160,
            keywordStyle: "space_separated",
        },
        writingInstructions: "Write in clear, professional American English. Use active voice. Vary sentence length.",
        localContext: {
            currency: "USD",
            currencySymbol: "$",
            dateFormat: "MM/DD/YYYY",
            exampleBrands: ["Google", "Amazon", "Shopify", "HubSpot"],
            searchEngines: ["Google", "Bing"],
            socialPlatforms: ["LinkedIn", "Twitter", "Instagram"],
        },
    },
    {
        code: "hi",
        name: "Hindi",
        nativeName: "हिन्दी",
        flag: "🇮🇳",
        direction: "ltr",
        script: "devanagari",
        primaryCountry: "India",
        hreflang: "hi",
        locale: "hi_IN",
        googleSearchLocale: "hi-IN",
        fontStack: "'Noto Sans Devanagari', sans-serif",
        seo: {
            titleMaxChars: 55,
            descMaxChars: 150,
            keywordStyle: "space_separated",
        },
        writingInstructions: "Write in modern Hindi (Hinglish is acceptable for technical terms). Use simple vocabulary accessible to Class 10+ educated readers. Avoid overly formal Sanskrit-heavy language. Use ₹ for currency. Reference Indian context: Jio, Flipkart, Paytm, Zomato. Tone should be helpful and conversational like a knowledgeable friend. Use 'आप' (formal you) throughout.",
        localContext: {
            currency: "INR",
            currencySymbol: "₹",
            dateFormat: "DD/MM/YYYY",
            exampleBrands: ["Jio", "Flipkart", "Paytm", "Zomato", "Infosys", "Tata", "HDFC"],
            searchEngines: ["Google India"],
            socialPlatforms: ["WhatsApp", "Instagram", "YouTube", "ShareChat"],
        },
    },
    {
        code: "es",
        name: "Spanish",
        nativeName: "Español",
        flag: "🇪🇸",
        direction: "ltr",
        script: "latin",
        primaryCountry: "Spain",
        hreflang: "es",
        locale: "es_ES",
        googleSearchLocale: "es-ES",
        fontStack: "var(--font-sans), sans-serif",
        seo: {
            titleMaxChars: 60,
            descMaxChars: 160,
            keywordStyle: "space_separated",
        },
        writingInstructions: "Write in neutral Spanish that works for both Spain and Latin America. Avoid region-specific slang. Use 'usted' for formal tone. Professional but warm register.",
        localContext: {
            currency: "EUR/various",
            currencySymbol: "€/$",
            dateFormat: "DD/MM/YYYY",
            exampleBrands: ["Mercadona", "Santander", "Telefónica", "MercadoLibre", "Rappi"],
            searchEngines: ["Google"],
            socialPlatforms: ["WhatsApp", "Instagram"],
        },
    },
    {
        code: "fr",
        name: "French",
        nativeName: "Français",
        flag: "🇫🇷",
        direction: "ltr",
        script: "latin",
        primaryCountry: "France",
        hreflang: "fr",
        locale: "fr_FR",
        googleSearchLocale: "fr-FR",
        fontStack: "var(--font-sans), sans-serif",
        seo: {
            titleMaxChars: 60,
            descMaxChars: 160,
            keywordStyle: "space_separated",
        },
        writingInstructions: "Write in standard French (not Quebec or African French). Formal 'vous' form. French readers expect precise, well-structured prose. Logical flow is essential. Use AZERTY-friendly technical terms where relevant.",
        localContext: {
            currency: "EUR",
            currencySymbol: "€",
            dateFormat: "DD/MM/YYYY",
            exampleBrands: ["Orange", "BNP Paribas", "LVMH", "Carrefour"],
            searchEngines: ["Google"],
            socialPlatforms: ["Facebook", "Instagram"],
        },
    },
    {
        code: "de",
        name: "German",
        nativeName: "Deutsch",
        flag: "🇩🇪",
        direction: "ltr",
        script: "latin",
        primaryCountry: "Germany",
        hreflang: "de",
        locale: "de_DE",
        googleSearchLocale: "de-DE",
        fontStack: "var(--font-sans), sans-serif",
        seo: {
            titleMaxChars: 60,
            descMaxChars: 160,
            keywordStyle: "space_separated",
        },
        writingInstructions: "Write in standard German (Hochdeutsch). Germans expect thorough, accurate, well-sourced content. Use 'Sie' (formal). Compound words are fine and expected. Be precise — avoid vague claims. Engineering/quality focus resonates well with German audiences.",
        localContext: {
            currency: "EUR",
            currencySymbol: "€",
            dateFormat: "DD.MM.YYYY",
            exampleBrands: ["SAP", "Deutsche Bank", "BMW", "Bosch", "Zalando"],
            searchEngines: ["Google"],
            socialPlatforms: ["LinkedIn", "Instagram"],
        },
    },
    {
        code: "pt",
        name: "Portuguese",
        nativeName: "Português",
        flag: "🇧🇷",
        direction: "ltr",
        script: "latin",
        primaryCountry: "Brazil",
        hreflang: "pt-BR",
        locale: "pt_BR",
        googleSearchLocale: "pt-BR",
        fontStack: "var(--font-sans), sans-serif",
        seo: {
            titleMaxChars: 60,
            descMaxChars: 160,
            keywordStyle: "space_separated",
        },
        writingInstructions: "Write in Brazilian Portuguese (pt-BR), not European Portuguese. Warm, friendly tone. Brazilians prefer approachable, conversational content. Use 'você'. Reference Brazilian brands and market context.",
        localContext: {
            currency: "BRL",
            currencySymbol: "R$",
            dateFormat: "DD/MM/YYYY",
            exampleBrands: ["Nubank", "Mercado Livre", "iFood", "Totvs"],
            searchEngines: ["Google"],
            socialPlatforms: ["WhatsApp", "Instagram", "Facebook"],
        },
    },
    {
        code: "ar",
        name: "Arabic",
        nativeName: "العربية",
        flag: "🇸🇦",
        direction: "rtl",
        script: "arabic",
        primaryCountry: "Saudi Arabia",
        hreflang: "ar",
        locale: "ar_SA",
        googleSearchLocale: "ar-SA",
        fontStack: "'Noto Sans Arabic', 'Cairo', sans-serif",
        seo: {
            titleMaxChars: 55,
            descMaxChars: 150,
            keywordStyle: "space_separated",
        },
        writingInstructions: "Write in Modern Standard Arabic (Fusha) that is understood across the Arab world. Professional, respectful tone. Avoid dialect-specific expressions. Right-to-left text direction. Use Arabic numerals (٠١٢٣) or Western numerals as appropriate for context. Be culturally sensitive — the audience spans many countries.",
        localContext: {
            currency: "SAR/AED",
            currencySymbol: "﷼/د.إ",
            dateFormat: "DD/MM/YYYY",
            exampleBrands: ["STC", "Souq/Amazon", "Noon", "Careem"],
            searchEngines: ["Google"],
            socialPlatforms: ["Snapchat", "WhatsApp", "Instagram"],
        },
    },
    {
        code: "ja",
        name: "Japanese",
        nativeName: "日本語",
        flag: "🇯🇵",
        direction: "ltr",
        script: "cjk",
        primaryCountry: "Japan",
        hreflang: "ja",
        locale: "ja_JP",
        googleSearchLocale: "ja-JP",
        fontStack: "'Noto Sans JP', 'Hiragino Sans', sans-serif",
        seo: {
            titleMaxChars: 30,
            descMaxChars: 80,
            keywordStyle: "comma_separated",
        },
        writingInstructions: "Write in natural Japanese. Use 丁寧語 (polite form) with です/ます endings. Japanese readers expect structured, detailed content. Use appropriate kanji/kana mix. Short sentences preferred. Numbered lists and clear structure are highly valued. Avoid direct comparison criticism of brands.",
        localContext: {
            currency: "JPY",
            currencySymbol: "¥",
            dateFormat: "YYYY/MM/DD",
            exampleBrands: ["Rakuten", "SoftBank", "LINE", "Mercari", "Yahoo Japan"],
            searchEngines: ["Google Japan", "Yahoo Japan"],
            socialPlatforms: ["Line", "Twitter", "Instagram"],
        },
    },
    {
        code: "zh",
        name: "Chinese",
        nativeName: "中文",
        flag: "🇨🇳",
        direction: "ltr",
        script: "cjk",
        primaryCountry: "China",
        hreflang: "zh-CN",
        locale: "zh_CN",
        googleSearchLocale: "zh-CN",
        fontStack: "'Noto Sans SC', 'PingFang SC', sans-serif",
        seo: {
            titleMaxChars: 30,
            descMaxChars: 80,
            keywordStyle: "comma_separated",
        },
        writingInstructions: "Write in Simplified Chinese (zh-CN). Clear, practical tone. Chinese readers value concrete actionable information. Use 您 for formal address. Reference Chinese platforms and market context. Note: Baidu SEO rules differ from Google — use keyword density slightly higher (2-3%), shorter paragraphs.",
        localContext: {
            currency: "CNY",
            currencySymbol: "¥/元",
            dateFormat: "YYYY-MM-DD",
            exampleBrands: ["Alibaba", "Tencent", "ByteDance", "Meituan", "JD.com"],
            searchEngines: ["Baidu", "Sogou", "Bing China"],
            socialPlatforms: ["WeChat", "Douyin", "Red"],
        },
    },
    {
        code: "ko",
        name: "Korean",
        nativeName: "한국어",
        flag: "🇰🇷",
        direction: "ltr",
        script: "hangul",
        primaryCountry: "South Korea",
        hreflang: "ko",
        locale: "ko_KR",
        googleSearchLocale: "ko-KR",
        fontStack: "'Noto Sans KR', 'Apple SD Gothic Neo', sans-serif",
        seo: {
            titleMaxChars: 35,
            descMaxChars: 90,
            keywordStyle: "space_separated",
        },
        writingInstructions: "Write in formal Korean (합쇼체). Korean readers expect well-organized, thorough content. Use 존댓말 (honorific speech). Numbered steps and organized lists are effective. Korean digital market is highly mobile-first — consider mobile reading experience in structure.",
        localContext: {
            currency: "KRW",
            currencySymbol: "₩",
            dateFormat: "YYYY. MM. DD.",
            exampleBrands: ["Samsung", "Kakao", "Naver", "Coupang", "Krafton"],
            searchEngines: ["Naver", "Kakao", "Google Korea"],
            socialPlatforms: ["KakaoTalk", "Instagram", "YouTube"],
        },
    },
    {
        code: "it",
        name: "Italiano",
        nativeName: "Italiano",
        flag: "🇮🇹",
        direction: "ltr",
        script: "latin",
        primaryCountry: "Italy",
        hreflang: "it",
        locale: "it_IT",
        googleSearchLocale: "it-IT",
        fontStack: "var(--font-sans), sans-serif",
        seo: {
            titleMaxChars: 60,
            descMaxChars: 160,
            keywordStyle: "space_separated",
        },
        writingInstructions: "Write in standard Italian. Warm but professional tone. Italians appreciate elegance in writing. Use 'Lei' for formal tone. Reference Italian brands and market context. Good structure with clear flow.",
        localContext: {
            currency: "EUR",
            currencySymbol: "€",
            dateFormat: "DD/MM/YYYY",
            exampleBrands: ["Enel", "Intesa Sanpaolo", "Ferrero", "Luxottica"],
            searchEngines: ["Google"],
            socialPlatforms: ["WhatsApp", "Instagram"],
        },
    },
    {
        code: "ru",
        name: "Russian",
        nativeName: "Русский",
        flag: "🇷🇺",
        direction: "ltr",
        script: "cyrillic",
        primaryCountry: "Russia",
        hreflang: "ru",
        locale: "ru_RU",
        googleSearchLocale: "ru-RU",
        fontStack: "'Noto Sans', sans-serif",
        seo: {
            titleMaxChars: 55,
            descMaxChars: 150,
            keywordStyle: "space_separated",
        },
        writingInstructions: "Write in standard Russian. Professional but accessible tone. Use formal 'вы'. Russian readers value depth and thoroughness. Yandex SEO differs from Google — prioritize natural keyword usage, avoid stuffing. Reference Russian market context where relevant.",
        localContext: {
            currency: "RUB",
            currencySymbol: "₽",
            dateFormat: "DD.MM.YYYY",
            exampleBrands: ["Yandex", "Sberbank", "VK", "Wildberries", "Ozon"],
            searchEngines: ["Yandex", "Google Russia"],
            socialPlatforms: ["VK", "Telegram", "WhatsApp"],
        },
    },
];
