'use client'

import React from 'react';
import LegalLayout from '@/components/legal/LegalLayout';
import { LegalSection } from '@/components/legal/LegalSection';
import { LegalCallout } from '@/components/legal/LegalCallout';
import { useLegalTOC } from '@/hooks/useLegalTOC';

const SECTIONS = [
    { id: 'introduction', title: '1. Introduction' },
    { id: 'acceptance', title: '2. Acceptance of Terms' },
    { id: 'eligibility', title: '3. Eligibility' },
    { id: 'accounts', title: '4. Accounts and Security' },
    { id: 'content', title: '5. Content Ownership and License' },
    { id: 'prohibited', title: '6. Prohibited Conduct' },
    { id: 'payments', title: '7. Payments and Credits' },
    { id: 'refunds', title: '8. Refund Policy' },
    { id: 'disclaimer', title: '9. Disclaimer of Warranties' },
    { id: 'liability', title: '10. Limitation of Liability' },
    { id: 'indemnity', title: '11. Indemnification' },
    { id: 'termination', title: '12. Termination' },
    { id: 'governing-law', title: '13. Governing Law' },
];

export function TermsContent() {
    const activeId = useLegalTOC(SECTIONS.map(s => s.id));

    return (
        <LegalLayout
            label="Legal"
            title="Terms of Service"
            subtitle="The rules of the road for using Recuvix. Standard SaaS terms designed for clarity and fairness."
            lastUpdated="March 17, 2026"
            effectiveDate="March 17, 2026"
            sections={SECTIONS}
            activeId={activeId}
        >
            <LegalSection id="introduction" title="1. Introduction">
                <p>
                    Welcome to Recuvix. These Terms of Service ("Terms") govern your access to and use of the Recuvix platform, website, and services ("Service") provided by Recuvix Technologies ("we", "us", or "our").
                </p>
                <p>
                    By creating an account or using the Service, you agree to be bound by these Terms.
                </p>
                <LegalCallout>
                    <strong>Plain English summary:</strong> Be respectful, don't use the tool for spam or illegal content, and pay your bills. You own what you create. We aren't responsible if your AI-generated blog says something silly or doesn't rank as high as you hoped.
                </LegalCallout>
            </LegalSection>

            <LegalSection id="acceptance" title="2. Acceptance of Terms">
                <p>
                    If you are using the Service on behalf of an organisation, you represent that you have the authority to bind that organisation to these Terms. If you do not agree to these Terms, you may not use the Service.
                </p>
            </LegalSection>

            <LegalSection id="eligibility" title="3. Eligibility">
                <p>
                    You must be at least 18 years of age to use the Service. By using the Service, you represent and warrant that you meet this requirement and have the full right, power, and authority to enter into these Terms.
                </p>
            </LegalSection>

            <LegalSection id="accounts" title="4. Accounts and Security">
                <p>
                    <strong>Account creation:</strong> You must provide accurate and complete information when creating an account.
                </p>
                <p>
                    <strong>Security:</strong> You are responsible for maintaining the confidentiality of your account credentials. You are responsible for all activities that occur under your account.
                </p>
                <p>
                    <strong>Unauthorised use:</strong> You must notify us immediately at support@recuvix.in if you suspect any unauthorised use of your account.
                </p>
            </LegalSection>

            <LegalSection id="content" title="5. Content Ownership and License">
                <h3>5.1 Your content</h3>
                <p>
                    <strong>You own your content:</strong> You retain all ownership rights to the input data you provide and the blog content generated by the Service.
                </p>
                <p>
                    <strong>License to us:</strong> You grant us a limited, worldwide, non-exclusive license to process your content solely to provide and improve the Service (e.g., generating transcripts, formatting blogs).
                </p>

                <h3>5.2 Our content</h3>
                <p>
                    The Service, including its "look and feel," proprietary algorithms, and software, is owned by Recuvix Technologies and is protected by intellectual property laws.
                </p>
            </LegalSection>

            <LegalSection id="prohibited" title="6. Prohibited Conduct">
                <p>You agree not to:</p>
                <ul>
                    <li>Use the Service for any illegal purpose or to promote illegal activities.</li>
                    <li>Generate content that is defamatory, obscene, or promotes hate speech.</li>
                    <li>Use the Service to generate large-scale spam or deceptive content.</li>
                    <li>Attempt to reverse-engineer or hack the Service.</li>
                    <li>Abuse the "Managed Mode" credits or bypass rate limits.</li>
                    <li>Share your account or API keys with unauthorised third parties.</li>
                </ul>
            </LegalSection>

            <LegalSection id="payments" title="7. Payments and Credits">
                <p>
                    <strong>Credits:</strong> Recuvix operate on a credit-based system. Each blog generation or voice transcription consumes a specific number of credits.
                </p>
                <p>
                    <strong>Purchases:</strong> All payments are processed via Razorpay. Prices are inclusive of GST as applicable in India.
                </p>
                <p>
                    <strong>Credit expiry:</strong> Credits purchased do not expire as long as your account remains active.
                </p>
            </LegalSection>

            <LegalSection id="refunds" title="8. Refund Policy">
                <p>
                    Due to the nature of AI processing costs, we generally do not offer refunds once credits have been consumed.
                </p>
                <p>
                    <strong>Unused credits:</strong> If you have purchased a pack and haven't used any credits, you may request a refund within 7 days of purchase.
                </p>
                <p>
                    <strong>Technical errors:</strong> If a generation fails due to a platform error, we will automatically refund the specific credit to your balance.
                </p>
            </LegalSection>

            <LegalSection id="disclaimer" title="9. Disclaimer of Warranties">
                <p>
                    THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE." WE DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE ACCURACY OF AI-GENERATED CONTENT OR ITS PERFORMANCE IN SEARCH ENGINES.
                </p>
                <p>
                    AI models can "hallucinate" or provide incorrect information. You are solely responsible for fact-checking and reviewing all content before publishing.
                </p>
            </LegalSection>

            <LegalSection id="liability" title="10. Limitation of Liability">
                <p>
                    TO THE MAXIMUM EXTENT PERMITTED BY LAW, RECUVIX TECHNOLOGIES SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, INCLUDING LOSS OF PROFITS, DATA, OR SEO RANKINGS.
                </p>
            </LegalSection>

            <LegalSection id="indemnity" title="11. Indemnification">
                <p>
                    You agree to indemnify and hold Recuvix Technologies harmless from any claims arising out of your use of the Service or violation of these Terms.
                </p>
            </LegalSection>

            <LegalSection id="termination" title="12. Termination">
                <p>
                    <strong>By you:</strong> You may terminate your account at any time.
                </p>
                <p>
                    <strong>By us:</strong> We may suspend or terminate your access for violation of these Terms or for failure to pay.
                </p>
            </LegalSection>

            <LegalSection id="governing-law" title="13. Governing Law">
                <p>
                    These Terms are governed by the laws of India. Any disputes shall be subject to the exclusive jurisdiction of the courts in Bangalore, Karnataka.
                </p>
                <p>
                    For any questions regarding these Terms, contact <strong>legal@recuvix.in</strong>.
                </p>
            </LegalSection>
        </LegalLayout>
    );
}
