'use client';

import React, { useState } from 'react';
import { useHistory } from '@/hooks/useHistory';
import { HistorySidebar } from './HistorySidebar';
import { HistorySearchBar } from './HistorySearchBar';
import { HistorySortFilter } from './HistorySortFilter';
import { HistoryGrid } from './HistoryGrid';
import { HistoryEmptyState } from './HistoryEmptyState';
import { HistoryBulkActionBar } from './HistoryBulkActionBar';
import { StorageManagementModal } from './StorageManagementModal';
import { TagEditor } from './TagEditor';
import {
    Popover,
    PopoverContent,
    PopoverTrigger,
} from "@/components/ui/popover";
import { useRouter } from 'next/navigation';

export const HistoryPage: React.FC<{ workspaceId?: string }> = ({ workspaceId }) => {
    const router = useRouter();
    const history = useHistory(workspaceId);
    const [isStorageModalOpen, setIsStorageModalOpen] = useState(false);
    const [tagEditorId, setTagEditorId] = useState<string | null>(null);

    const handleAction = () => {
        if (history.index.length === 0) {
            router.push('/');
        } else {
            history.clearFilters();
        }
    };

    return (
        <div className="max-w-[1400px] mx-auto px-6 py-12 flex gap-8">
            {/* Sidebar */}
            <HistorySidebar
                index={history.index}
                activeFilters={history.activeFilters}
                onFilterChange={history.setFilter}
                uniqueCountries={history.uniqueCountries}
                uniqueModels={history.uniqueModels}
                allTags={history.allTags}
                totalWords={history.totalWords}
                storageUsage={history.storageUsage}
                onManageStorage={() => setIsStorageModalOpen(true)}
            />

            {/* Main Content */}
            <div className="flex-1 min-w-0">
                <div className="mb-8">
                    <h1 className="text-3xl font-black text-white mb-2">
                        {workspaceId ? 'Team Blogs' : 'Blog History'}
                    </h1>
                    <p className="text-muted-foreground text-sm">
                        {workspaceId ? 'Manage, search, and export articles generated by your team.' : 'Manage, search, and export your previously generated blogs.'}
                    </p>
                </div>

                <div className="mb-10">
                    <HistorySearchBar
                        value={history.searchQuery}
                        onChange={history.setSearchQuery}
                        resultCount={history.searchQuery ? history.filteredEntries.length : undefined}
                    />
                </div>

                {history.index.length > 0 && (
                    <HistorySortFilter
                        resultCount={history.filteredEntries.length}
                        viewMode={history.viewMode}
                        setViewMode={history.setViewMode}
                        sortBy={history.sortBy}
                        setSortBy={history.setSortBy}
                    />
                )}

                {history.filteredEntries.length > 0 ? (
                    <HistoryGrid
                        entries={history.filteredEntries}
                        viewMode={history.viewMode}
                        selectedIds={history.selectedIds}
                        onSelect={(id) => history.isSelected(id) ? history.deselectEntry(id) : history.selectEntry(id)}
                        onOpen={history.openBlog}
                        onDownload={history.downloadBlog}
                        onToggleStar={history.toggleStar}
                        onDelete={history.deleteEntry}
                        onRegenerate={history.regenerateBlog}
                        onEditTags={(id) => setTagEditorId(id)}
                    />
                ) : (
                    <HistoryEmptyState
                        type={history.index.length === 0 ? 'no-blogs' : 'no-results'}
                        onAction={handleAction}
                    />
                )}
            </div>

            {/* Tag Editor Popover (Hidden trigger, programmatic open) */}
            <Popover open={!!tagEditorId} onOpenChange={(open: boolean) => !open && setTagEditorId(null)}>
                <PopoverTrigger className="hidden" />
                <PopoverContent className="p-0 border-none bg-transparent shadow-none" side="right" align="start">
                    {tagEditorId && (
                        <TagEditor
                            tags={history.index.find(e => e.id === tagEditorId)?.tags || []}
                            suggestions={history.allTags}
                            onAdd={(tag) => history.addTag(tagEditorId, tag)}
                            onRemove={(tag) => history.removeTag(tagEditorId, tag)}
                        />
                    )}
                </PopoverContent>
            </Popover>

            {/* Modals & Bars */}
            <HistoryBulkActionBar
                selectedCount={history.selectedIds.length}
                onClear={history.clearSelection}
                onStarAll={history.starSelected}
                onDownloadAll={history.downloadSelected}
                onDeleteAll={history.deleteSelected}
            />

            <StorageManagementModal
                isOpen={isStorageModalOpen}
                onClose={() => setIsStorageModalOpen(false)}
                storageUsage={history.storageUsage}
                onClearNonStarred={history.clearNonStarred}
                onClearAll={history.clearAll}
                onExportAll={history.exportAll}
            />
        </div>
    );
};
